### ISSUE TITLE
Does not work with react 15.1.0

### ISSUE THREAD

**Issue by pke** [adambbecker/react-style-transition-group#1]
Thanks for this nice stylesheet less version :)
It worked great until I upgraded to react `15.1.0`

Now it throws:

![image](https://cloud.githubusercontent.com/assets/164625/15923905/c7bb31f6-2e2f-11e6-9311-6f39df8d6484.png)

**Edit**

The problem is actually with react 15. They introduced some `__DEV__` only code, that does not check if the `CSSPropertyOperations.setValueForStyles` actually gets the 3rd `component` arg.

```
setValueForStyles: function(node, styles, component) {
    if (__DEV__) {
      ReactInstrumentation.debugTool.onHostOperation(
        component._debugID,
        'update styles',
        styles
      );
    }
```

I could fix it (for now) like this:

```
const REACT15_COMPONENT_HACK = { _debugID: 666, _currentElement: {} }

CSSPropertyOperations.setValueForStyles(node, transitionStyles, REACT15_COMPONENT_HACK)
```

I mentioned it over there https://github.com/facebook/react/pull/6754#issuecomment-224840800

**Comment by gaearon** [comment]
`CSSPropertyOperations.setValueForStyles` is not a public API. If you’re using it, expect it to break without warnings 😉 . You will also see problems when we switch to flat bundles, and `react/lib/*` will become completely inaccessible.

There is nothing that should be done in React to fix this. The method signature now expects component to always be there, and to fix it, the best way is to fork that logic and place it directly in this library. It is not a public API that we intend to support.

**Comment by pke** [comment]
Thanks for commenting here @gaearon 
I understand all what you say.
One question though: I wonder why style sheet class transitions are part of react and this thing here was never considered? I very much prefer inline styles over style sheets.

Do you know any other lib that does react transitions with styles instead of classnames?

**Comment by gaearon** [comment]
Check out react-motion, I think it does what you want.

TransitionGroup inside React is going to be unsupported in the future anyway so that's why it didn't pick up more functionality.
